navel/catalogue/urls.py
from django.conf.urls import url

from . import views

app_name = 'catalogue'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<brand_id>[\w-]+)/$', views.brand, name='brand'),
    url(r'^(?P<brand_id>[\w-]+)/(?P<slug>[\w-]+)/$', views.model, name='model'),
]

navel/navel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from navel import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^catalogue/', include('catalogue.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

navel/catalogue/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Conditioner(models.Model):
    title = models.CharField(max_length=255, verbose_name=u'Название модели')
    slug = models.SlugField(max_length=255, db_index=True, blank=True, unique=True)
    inverter = models.BooleanField(default=False, verbose_name=u'Инвертор')
    brand = models.ForeignKey('Brand', related_name='conditioner', verbose_name=u'Бренд', to_field='title')
    type = models.ForeignKey('Type', related_name='conditioner', verbose_name=u'Тип')
    block_type = models.ForeignKey('BlockType', related_name='conditioner', verbose_name=u'Тип внутреннего блока')
    image = models.ImageField(upload_to='conditioners', blank=True, verbose_name=u'Изображение')
    date_added = models.DateTimeField(auto_now_add=True, verbose_name=u'Дата добавления')

    class Meta:
        verbose_name = u'Кондиционер'
        verbose_name_plural = u'Кондиционеры'

    def __unicode__(self):
        return self.title


class Brand(models.Model):
    title = models.CharField(max_length=100, verbose_name=u'Название', unique=True)
    description = models.TextField(verbose_name=u'Описание', blank=True)

    class Meta:
        verbose_name = u'Бренд'
        verbose_name_plural = u'Бренды'

    def __unicode__(self):
        return self.title


class Type(models.Model):
    title = models.CharField(max_length=50, verbose_name=u'Название')

    class Meta:
        verbose_name = u'Тип'
        verbose_name_plural = u'Типы'

    def __unicode__(self):
        return self.title


class BlockType(models.Model):
    title = models.CharField(max_length=50, verbose_name=u'Название')

    class Meta:
        verbose_name = u'Тип внутреннего блока'
        verbose_name_plural = u'Типы внутреннего блока'

    def __unicode__(self):
        return self.title

navel/catalogue/forms.py
# -*- coding: utf-8 -*-
from django import forms

from catalogue.models import Conditioner, Brand, Type, BlockType


class CatalogueFilterForm(forms.Form):
    brand__in = forms.ModelMultipleChoiceField(queryset=Brand.objects.all().order_by('title'), required=False,
                                               widget=forms.CheckboxSelectMultiple(), label=u'Бренд')
    type__in = forms.ModelMultipleChoiceField(queryset=Type.objects.all().order_by('title'), required=False,
                                              widget=forms.CheckboxSelectMultiple(), label=u'Тип')

    block_type__in = forms.ModelMultipleChoiceField(queryset=BlockType.objects.all().order_by('title'), required=False,
                                                    widget=forms.CheckboxSelectMultiple(),
                                                    label=u'Тип внутреннего блока')

    inverter = forms.BooleanField(required=False, label=u'Инвертер')

    def clean(self):
        cleaned_data = super(CatalogueFilterForm, self).clean()

        for k in cleaned_data.keys():
            if not cleaned_data.get(k, False):
                del cleaned_data[k]

        return cleaned_data

    def as_selected(self):
        # "Returns this form rendered as HTML <p>s."
        output = ''
        for name, field in self.fields.items():
            bf = self[name]
            if bf.data:
                output += '%s ' % bf.label
        # for key in self.data:
        #     # get values of each key
        #     values = self.data.getlist(key)
            # todo: parse it, get title of each value
        return output


class ConditionerAdminForm(forms.ModelForm):
    class Meta:
        model = Conditioner
        exclude = ()

navel/catalogue/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404

from catalogue.forms import CatalogueFilterForm
from models import Conditioner, Brand, Type, BlockType


def index(request, brand_title=None):
    conditioners = Conditioner.objects.all()
    filter_form = CatalogueFilterForm(request.GET)

    if brand_title:
        conditioners = conditioners.filter(brand__title=brand_title)
        brand = get_object_or_404(Brand, title=brand_title)
        filter_form.data = {'brand__in': [brand.pk]}

    if filter_form.is_valid():
        conditioners = conditioners.filter(**filter_form.cleaned_data)

    context = {
        'conditioners': conditioners,
        'filter_form': filter_form,
    }
    return render(request, 'catalogue/catalogue.html', context)


def brand(request, brand_id):
    return index(request, brand_title=brand_id)


def model(request, brand_id, slug):
    conditioner = get_object_or_404(Conditioner, brand_id=brand_id, slug=slug)
    return render(request, 'catalogue/model.html', context={'conditioner': conditioner})

navel/catalogue/templates/catalogue/catalogue.html
{% extends 'catalogue/index.html' %}
{% load thumbnail %}

{% block content %}
    <div class="uk-container">
        <div uk-grid>

            <div class="uk-width-1-4">

                <h2>Filters</h2>
                <form method="get" class="uk-form-stacked" action="/catalogue/">
                    {{ filter_form }}<br>
                    <button class="uk-button uk-button-default" type="submit"><span uk-icon="icon: search"></span> Search</button>
                </form>
            </div>
            <div class="uk-width-3-4">

            {% if filter_form.data %}
                <div>
                    Your choice:
                {{ filter_form.as_selected|safe }}
                </div>
            {% endif %}
                <h2>List of Conditioners</h2>
                <div class="uk-grid-small uk-child-width-1-2@s uk-child-width-1-3@m" uk-grid>
                    {% for conditioner in conditioners %}
                        <div>
                            <div class="uk-card uk-card-primary ul-light">
                                <div class="uk-card-media-top">
                                    {% thumbnail conditioner.image "400x400" crop="center" as im %}
                                        <img src="{{ im.url }}" alt="{{ conditioner.title }}">
                                    {% endthumbnail %}
                                </div>
                                <div class="uk-card-body">
                                    <a href="{% url 'catalogue:model' conditioner.brand_id conditioner.slug %}">
                                        <h3 class="uk-card-title">{{ conditioner.title|truncatechars:15 }}</h3>
                                    </a>
                                    <p>
                                        Brand: <a href="{% url 'catalogue:brand' conditioner.brand_id %}">{{ conditioner.brand }}</a>
                                    </p>
                                    <p>Type: {{ conditioner.type }}</p>
                                    <p>Block type: {{ conditioner.block_type }}</p>
                                    <p>Inverter: {{ conditioner.inverter }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

navel/catalogue/templates/catalogue/footer.html
{% block footer %}
<footer class="uk-section uk-section-primary uk-light">
{%  now 'Y' %}, Компания &laquo;Кондиционер&raquo;
</footer>
{% endblock %}

navel/catalogue/templates/catalogue/index.html
{% load main_menu %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.20/css/uikit.min.css" />

</head>
<body>
{% main_menu %}

{% block content %}
{% endblock %}
{% block model %}

{% endblock %}
{% block footer %}
{% include 'catalogue/footer.html' %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.20/js/uikit.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.20/js/uikit-icons.min.js"></script>

</body>
</html>

navel/catalogue/templates/catalogue/menu.html
<nav class="uk-navbar-container" uk-navbar>
    <div class="uk-navbar-left">
        <ul class="uk-navbar-nav">
            <li><a href="">Главная</a></li>
            <li{% if active == 'catalogue' %} class="uk-active"{% endif %}><a href="{% url 'catalogue:index' %}">Каталог</a></li>
        </ul>
    </div>
</nav>

navel/catalogue/templates/catalogue/model.html
{% extends 'catalogue/index.html' %}
{% block model %}
    <div class="uk-card uk-card-primary uk-grid-collapse uk-child-width-1-2@s uk-margin" uk-grid>
        <div class="uk-card-media-left uk-cover-container">
            <img src="{{ conditioner.image.url }}" alt="{{ conditioner.title }}">
        </div>
        <div>
            <div class="uk-card-body">
                <h3>{{ conditioner.title }}</h3>
                <p>Type: {{ conditioner.type }}</p>
                <p>Block type: {{ conditioner.block_type }}</p>
                <p>Inverter: {{ conditioner.inverter }}</p>
            </div>
        </div>
    </div>
{% endblock %}